# Generated by Django 6.0.5 on 2026-05-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('theme', models.CharField(default='Modern', max_length=50)),
                ('business_type', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('services_json', models.JSONField(blank=True, default=list)),
                ('gallery_json', models.JSONField(blank=True, default=list)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='websites.website')),
            ],
        ),
    ]
