# Generated by Django 4.2 on 2026-06-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='custom_html',
            field=models.TextField(blank=True),
        ),
    ]
