# Generated by Django 4.2 on 2026-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_websitecontent_custom_css_websitecontent_custom_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='products_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
