# Generated by Django 4.2 on 2026-06-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_websitecontent_products_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='settings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
