# Generated by Django 4.2 on 2026-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_websitecontent_settings_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='custom_blocks_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
