# Generated by Django 4.2 on 2026-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_websitecontent_custom_blocks_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='visitors_count',
            field=models.IntegerField(default=0),
        ),
    ]
