# Generated by Django 4.2 on 2026-07-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_website_visitors_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
