# Generated by Django 4.2 on 2026-07-31 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('CLIENT', 'Client')], default='AGENT', max_length=20),
        ),
    ]
