# Generated by Django 4.2 on 2026-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_agent_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
