# Generated by Django 4.2 on 2026-08-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_has_completed_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
